### ISSUE TITLE
Handling of "/" in title

### ISSUE THREAD

**Issue by Baine** [RicterZ/nhentai#142]
id 262707
output folder is created as "[262707][hiroya][(C95) [Hirojuu Renshuuchou (Hiroya)] Chaldea Life II (Fate"
with subolder "Grand Order) [English] [Sinon Granaxia]]" which then holds the files

noticed this when having it create a CBZ, see error message below:
error message:
```
[11:33:49] [INFO] Writing CBZ file to path: ./[262707][hiroya][(C95) [Hirojuu Renshuuchou (Hiroya)] Chaldea Life II (Fate/Grand Order) [English] [Sinon Granaxia]]/../[262707][hiroya][(C95) [Hirojuu Renshuuchou (Hiroya)] Chaldea Life II (Fate/Grand Order) [English] [Sinon Granaxia]].cbz
Traceback (most recent call last):
  File "/usr/bin/nhentai", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.4.0', 'console_scripts', 'nhentai')())
  File "/usr/lib/python3.8/site-packages/nhentai-0.4.0-py3.8.egg/nhentai/command.py", line 88, in main
    generate_cbz(options.output_dir, doujinshi, options.rm_origin_dir)
  File "/usr/lib/python3.8/site-packages/nhentai-0.4.0-py3.8.egg/nhentai/utils.py", line 186, in generate_cbz
    with zipfile.ZipFile(cbz_filename, 'w') as cbz_pf:
  File "/usr/lib/python3.8/zipfile.py", line 1250, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: './[262707][hiroya][(C95) [Hirojuu Renshuuchou (Hiroya)] Chaldea Life II (Fate/Grand Order) [English] [Sinon Granaxia]]/../[262707][hiroya][(C95) [Hirojuu Renshuuchou (Hiroya)] Chaldea Life II (Fate/Grand Order) [English] [Sinon Granaxia]].cbz'
```

**Comment by pri-pro** [comment]
It can be skipped by formating output doujinshi folder name (without the title)
but this is NOT a solution of the bug.
