### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MCBBC** [RicterZ/nhentai#145]
Traceback (most recent call last):
  File "/usr/bin/nhentai", line 11, in <module>
    load_entry_point('nhentai==0.4.0', 'console_scripts', 'nhentai')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/nhentai-0.4.0-py2.7.egg/nhentai/command.py", line 8, in <module>
    from nhentai.cmdline import cmd_parser, banner
  File "/usr/lib/python2.7/site-packages/nhentai-0.4.0-py2.7.egg/nhentai/cmdline.py", line 13, in <module>
    from nhentai.utils import urlparse, generate_html, generate_main_html, DB
  File "/usr/lib/python2.7/site-packages/nhentai-0.4.0-py2.7.egg/nhentai/utils.py", line 12, in <module>
    import img2pdf
  File "/usr/lib/python2.7/site-packages/img2pdf-0.3.6-py2.7.egg/img2pdf.py", line 2360
    nonlocal infiles
                   ^
SyntaxError: invalid syntax

**Comment by MCBBC** [comment]
我把 utils.py 里的 import img2pdf 注释掉就正常了

**Comment by SnekNOTSnake** [comment]
I also had the same issue before. Solved it by installing the package with python 3.

**Comment by RicterZ** [comment]
img2pdf 的问题，可以重装下
