### ISSUE TITLE
Cannot list or download favourites

### ISSUE THREAD

**Issue by frost90909090** [RicterZ/nhentai#150]
When i use the command "nhentai -F" on linux it displays the following message:
[22:40:26] [INFO] nHentai ver 0.4.0: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[22:40:26] [INFO] Using mirror: https://nhentai.net
Traceback (most recent call last):
  File "/usr/local/bin/nhentai", line 11, in <module>
    load_entry_point('nhentai==0.4.0', 'console_scripts', 'nhentai')()
  File "/home/USERNAME/.local/lib/python3.8/site-packages/nhentai/command.py", line 28, in main
    check_cookie()
  File "/home/USERNAME/.local/lib/python3.8/site-packages/nhentai/utils.py", line 30, in check_cookie
    response = request('get', constant.BASE_URL).text
  File "/home/USERNAME.local/lib/python3.8/site-packages/nhentai/utils.py", line 26, in request
    return getattr(session, method)(url, proxies=constant.PROXY, verify=False, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1281, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.8/http/client.py", line 1213, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 0: ordinal not in range(256)

What should i do?

**Comment by frost90909090** [comment]
I found the error
on this file "/usr/lib/python3.8/http/client.py", line 1213 change:
values[i] = one_value.encode('latin-1')
to
values[i] = one_value.encode('utf-8')
