### ISSUE TITLE
Pdf functionallity broken

### ISSUE THREAD

**Issue by bill88t** [RicterZ/nhentai#153]
WARNING:root:Image contains transparency which cannot be retained in PDF.
WARNING:root:img2pdf will not perform a lossy operation.
WARNING:root:You can remove the alpha channel using imagemagick:
WARNING:root:  $ convert input.png -background white -alpha remove -alpha off output.png
Traceback (most recent call last):
  File "/usr/local/bin/nhentai", line 11, in <module>
    load_entry_point('nhentai==0.4.0', 'console_scripts', 'nhentai')()
  File "/usr/local/lib/python3.8/dist-packages/nhentai-0.4.0-py3.8.egg/nhentai/command.py", line 90, in main
    generate_pdf(options.output_dir, doujinshi, options.rm_origin_dir)
  File "/usr/local/lib/python3.8/dist-packages/nhentai-0.4.0-py3.8.egg/nhentai/utils.py", line 217, in generate_pdf
    pdf_f.write(img2pdf.convert(full_path_list))
  File "/usr/local/lib/python3.8/dist-packages/img2pdf-0.4.0-py3.8.egg/img2pdf.py", line 2032, in convert
  File "/usr/local/lib/python3.8/dist-packages/img2pdf-0.4.0-py3.8.egg/img2pdf.py", line 1409, in read_images
  File "/usr/local/lib/python3.8/dist-packages/img2pdf-0.4.0-py3.8.egg/img2pdf.py", line 1186, in get_imgmetadata
img2pdf.AlphaChannelError: Refusing to work on images with alpha channel

**Comment by bill88t** [comment]
Kubuntu 20.04

**Comment by RicterZ** [comment]
img2pdf's issue, maybe not be fixed.
