### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Criarino** [RicterZ/nhentai#198]
When I try to download a doujin I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/nhentai", line 11, in <module>
    load_entry_point('nhentai==0.4.11', 'console_scripts', 'nhentai')()
  File "/usr/local/lib/python2.7/dist-packages/nhentai-0.4.11-py2.7.egg/nhentai/command.py", line 77, in main
    doujinshi_list.append(Doujinshi(name_format=options.name_format, **doujinshi_info))
  File "/usr/local/lib/python2.7/dist-packages/nhentai-0.4.11-py2.7.egg/nhentai/doujinshi.py", line 43, in __init__
    self.filename = format_filename(name_format)
  File "/usr/local/lib/python2.7/dist-packages/nhentai-0.4.11-py2.7.egg/nhentai/utils.py", line 243, in format_filename
    filename = s.translate(str.maketrans(ban_chars, ' '*len(ban_chars))).strip()
AttributeError: type object 'str' has no attribute 'maketrans'

**Comment by mobrine1** [comment]
What command are you using, please post more details when filling an issue

**Comment by Criarino** [comment]
I used the normal nhentai --id=[ID] command (in this case nhentai --id=343567) but this also happens when I try to download favorites (nhentai --favorites --download --delay 1). I can still list the doujins, but not download

**Comment by RicterZ** [comment]
Use Python 3.x
https://docs.python.org/3.9/library/stdtypes.html?highlight=maketrans#str.maketrans
