### ISSUE TITLE
Favorites to a text file

### ISSUE THREAD

**Issue by Zweeflol** [RicterZ/nhentai#209]
Is there a possibility to export your favorites to a text file with the ID and Titles when using "nhentai --favorites"? Or "nhentai --favorites --page=1-5"?
e.g.   "nhentai --favorites --download --file favorites.txt" or  "nhentai --favorites --page=1-5 --download --file favorites.txt"

favorites.txt
ID			Title
103795		[Crazy Clover Club (Shirotsumekusa)] T-MOON COMPLEX Congratulations! 10th Anniversary (Various) [English]

**Comment by RicterZ** [comment]
Or just `nhentai -F --page=1 > output.txt`

**Comment by Zweeflol** [comment]
C:\Users\Win-7-x64\Desktop\New folder>nhentai -F --page=1 > output.txt
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\logger.py", line 59, in emit
    stream.write(message)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 38-44: character maps to <undefined>
Call stack:
  File "C:\Users\Win-7-x64\AppData\Local\Programs\Python\Python38\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.4.14', 'console_scripts', 'nhentai')())
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\command.py", line 21, in main
    banner()
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\cmdline.py", line 20, in banner
    logger.info(u'''nHentai ver %s: ??????? ????
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 954, in handle
    self.emit(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\logger.py", line 70, in emit
    self.handleError(record)
Message: "nHentai ver 0.4.14: ??????? ????\n       _   _            _        _\n _ __ | | | | ___ _ __ | |_ __ _(_)\n| '_ \\| |_| |/ _ \\ '_ \\| __/ _` | |\n| | | |  _  |  __/ | | | || (_| | |\n|_| |_
|_| |_|\\___|_| |_|\\__\\__,_|_|\n"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\logger.py", line 59, in emit
    stream.write(message)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2606' in position 471: character maps to <undefined>
Call stack:
  File "C:\Users\Win-7-x64\AppData\Local\Programs\Python\Python38\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.4.14', 'console_scripts', 'nhentai')())
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\command.py", line 64, in main
    print_doujinshi(doujinshis)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\parser.py", line 193, in print_doujinshi
    logger.info('Search Result || Found %i doujinshis \n' % doujinshi_list.__len__() +
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\logging\__init__.py", line 954, in handle
    self.emit(record)
  File "c:\users\win-7-x64\appdata\local\programs\python\python38\lib\site-packages\nhentai\logger.py", line 70, in emit
    self.handleError(record)
Message: "Search Result || Found 25 doujinshis
Arguments: ()

As for the output.txt
[02:10:29] [INFO] Using mirror: https://nhentai.net
[02:10:29] [INFO] Using viewer template "default"
[02:10:29] [INFO] Login successfully! Your username:
[02:10:29] [WARNING] You do not specify --download option
[02:10:29] [INFO] Getting doujinshi ids of page 1
[02:10:30] [INFO] All done.

**Comment by RicterZ** [comment]
It's a charset problem. Try set env var `PYTHONIOENCODING` to `utf-8`.

ref: https://stackoverflow.com/questions/16346914/python-3-2-unicodeencodeerror-charmap-codec-cant-encode-character-u2013-i

**Comment by Zweeflol** [comment]
> 
> 
> It's a charset problem. Try set env var `PYTHONIOENCODING` to `utf-8`.
> 
> ref: https://stackoverflow.com/questions/16346914/python-3-2-unicodeencodeerror-charmap-codec-cant-encode-character-u2013-i

Thnaks! this did the job.
chcp 65001
set PYTHONIOENCODING=utf-8
