### ISSUE TITLE
Strugglebussing

### ISSUE THREAD

**Issue by AkiraWhitlock** [RicterZ/nhentai#240]
Installing on ubuntu, trying to figure out what all is going wrong.

running install
running bdist_egg
running egg_info
writing requirements to nhentai.egg-info/requires.txt
writing nhentai.egg-info/PKG-INFO
writing top-level names to nhentai.egg-info/top_level.txt
writing dependency_links to nhentai.egg-info/dependency_links.txt
writing entry points to nhentai.egg-info/entry_points.txt
reading manifest file 'nhentai.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.md'
writing manifest file 'nhentai.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/doujinshi.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/cmdline.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/downloader.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/utils.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/__init__.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/serializer.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/util.py -> build/bdist.linux-x86_64/egg/nhentai
creating build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/main.js -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/main.css -> build/bdist.linux-x86_64/egg/nhentai/viewer
creating build/bdist.linux-x86_64/egg/nhentai/viewer/default
copying build/lib.linux-x86_64-2.7/nhentai/viewer/default/scripts.js -> build/bdist.linux-x86_64/egg/nhentai/viewer/default
copying build/lib.linux-x86_64-2.7/nhentai/viewer/default/styles.css -> build/bdist.linux-x86_64/egg/nhentai/viewer/default
copying build/lib.linux-x86_64-2.7/nhentai/viewer/default/index.html -> build/bdist.linux-x86_64/egg/nhentai/viewer/default
creating build/bdist.linux-x86_64/egg/nhentai/viewer/minimal
copying build/lib.linux-x86_64-2.7/nhentai/viewer/minimal/scripts.js -> build/bdist.linux-x86_64/egg/nhentai/viewer/minimal
copying build/lib.linux-x86_64-2.7/nhentai/viewer/minimal/styles.css -> build/bdist.linux-x86_64/egg/nhentai/viewer/minimal
copying build/lib.linux-x86_64-2.7/nhentai/viewer/minimal/index.html -> build/bdist.linux-x86_64/egg/nhentai/viewer/minimal
copying build/lib.linux-x86_64-2.7/nhentai/viewer/main.html -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/logo.png -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/constant.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/logger.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/parser.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/command.py -> build/bdist.linux-x86_64/egg/nhentai
byte-compiling build/bdist.linux-x86_64/egg/nhentai/doujinshi.py to doujinshi.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/cmdline.py to cmdline.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/downloader.py to downloader.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/serializer.py to serializer.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/constant.py to constant.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/logger.py to logger.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/parser.py to parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/command.py to command.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/nhentai-0.4.16-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing nhentai-0.4.16-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/nhentai-0.4.16-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/nhentai-0.4.16-py2.7.egg
Extracting nhentai-0.4.16-py2.7.egg to /usr/local/lib/python2.7/dist-packages
nhentai 0.4.16 is already the active version in easy-install.pth
Installing nhentai script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/nhentai-0.4.16-py2.7.egg
Processing dependencies for nhentai==0.4.16
Searching for soupsieve
Reading https://pypi.org/simple/soupsieve/
Downloading https://files.pythonhosted.org/packages/e1/25/a3005eedafb34e1258458e8a4b94900a60a41a2b4e459e0e19631648a2a0/soupsieve-2.3.1.tar.gz#sha256=b8d49b1cd4f037c7082a9683dfa1801aa2597fb11c3a1155b7a5b94829b4f1f9
Best match: soupsieve 2.3.1
Processing soupsieve-2.3.1.tar.gz
Writing /tmp/easy_install-srd4oc/soupsieve-2.3.1/setup.cfg
Running soupsieve-2.3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-srd4oc/soupsieve-2.3.1/egg-dist-tmp-mmRQye
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    license='MIT',
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 449, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 691, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 738, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 783, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 710, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 736, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 921, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1189, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1175, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-srd4oc/soupsieve-2.3.1/setup.py", line 40, in <module>
    license='MIT',
  File "/tmp/easy_install-srd4oc/soupsieve-2.3.1/setup.py", line 11, in get_version
    
ImportError: No module named util

**Comment by RicterZ** [comment]
Use python3 please :)
