### ISSUE TITLE
[DEBUG] Slow down and retry (400837) Keep repeating. 怎么一直用不到 (TT)

### ISSUE THREAD

**Issue by xiaji0131** [RicterZ/nhentai#243]
this error pop out and idk how, maybe is the same issue same as last time

[DEBUG] Slow down and retry (400837)

**Comment by xiaji0131** [comment]
![image](https://user-images.githubusercontent.com/104619241/166112184-5a839a2d-c981-4f7a-b63f-b7bdf65261a9.png)

哪位大神可以救救我呀啊啊啊

**Comment by xiaji0131** [comment]
[00:18:11] [INFO] Using mirror: https://nhentai.net
[00:18:11] [INFO] Using viewer template "default"
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "c:\python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "c:\python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "c:\python39\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "c:\python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "c:\python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001B46BC53790>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "c:\python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "c:\python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nhentai.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B46BC53790>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.4.16', 'console_scripts', 'nhentai')())
  File "c:\python39\lib\site-packages\nhentai\command.py", line 40, in main
    check_cookie()
  File "c:\python39\lib\site-packages\nhentai\utils.py", line 31, in check_cookie
    response = request('get', constant.BASE_URL).text
  File "c:\python39\lib\site-packages\nhentai\utils.py", line 27, in request
    return getattr(session, method)(url, verify=False, **kwargs)
  File "c:\python39\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "c:\python39\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python39\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "c:\python39\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nhentai.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B46BC53790>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))


latest error update

**Comment by Criarino** [comment]
+1 this

**Comment by zwy000009** [comment]
按照本项目的readme使用git的方式重新安装nhentai，并按照说明设定cookie和useragent。
设定cookie和useragent
![image](https://user-images.githubusercontent.com/23279743/166151982-e8a08843-e1c3-48d7-bbbe-497eef39e559.png)
$ nhentai --cookie=“csrftoken=YOUR CSRFTOKEN;sessionid=YOUR SESSIONID;cf_clearance=YOUR CFCLEARANCE”
![image](https://user-images.githubusercontent.com/23279743/166151944-dfafc7ac-fde4-4845-8581-38e4ebe31178.png)
$ nhentai --useragent=“Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36”
验证是否设置成功
![image](https://user-images.githubusercontent.com/23279743/166152038-d9dee721-649c-4d4a-a27f-ed6078c7b0ad.png)

**Comment by RicterZ** [comment]
参考下 #246 ？

**Comment by xiaji0131** [comment]
嗯谢谢，因为现在家乡，明天回去试一下

**Comment by xiaji0131** [comment]
> 

我的情况只需要重新下载整个程式就行了， 谢谢。 只是做以下的步骤就行了

按照本项目的readme使用git的方式重新安装nhentai，并按照说明设定cookie。
设定cookie
$ nhentai --cookie=“csrftoken=YOUR CSRFTOKEN;sessionid=YOUR SESSIONID;cf_clearance=YOUR CFCLEARANCE”


for Eng users:

In my case, I just need to re-download the entire program, thank you. Just do the following steps

Reinstall nhentai using git according to the readme of this project, and follow the instructions to set cookies.
Set cookies
$ nhentai --cookie=“csrftoken=YOUR CSRFTOKEN;sessionid=YOUR SESSIONID;cf_clearance=YOUR CFCLEARANCE”
