### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by noonealive1** [RicterZ/nhentai#256]
(tutorial_env) C:\Users\HP>nhentai --search="tag:shotacon, tag:mother" --page-range=1-5 --download
[19:58:57] [INFO] nHentai ver 0.4.16: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[19:58:57] [INFO] Using mirror: https://nhentai.net
[19:58:57] [INFO] Using viewer template "default"
[19:58:58] [ERROR] Cannot get your username, please check your cookie or use `nhentai --cookie` to set your cookie
[19:58:58] [INFO] Searching doujinshis using keywords "tag:shotacon, tag:mother" on page 1
[19:58:58] [CRITICAL] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\tutorial_env\Scripts\nhentai.exe\__main__.py", line 7, in <module>
  File "c:\users\hp\tutorial_env\lib\site-packages\nhentai\command.py", line 58, in main
    doujinshis = search_parser(options.keyword, sorting=options.sorting, page=page_list,
  File "c:\users\hp\tutorial_env\lib\site-packages\nhentai\parser.py", line 223, in search_parser
    if 'result' not in response:
UnboundLocalError: local variable 'response' referenced before assignment

please tell me how to fix it in simple language (noob)

**Comment by SandyRodgers-2017** [comment]
All that it is saying is that your cookie information is not correct and since it is not correct it cannot login and get values. 
How do you fix this  then? Well you plugin all of the information necessary for the --cookie flag to work. 
I use firefox to getting this information will be based off of that. 

First thing you do is login to nhentai using your browser in this case firefox. 
You then hit F12.
You then go to Storage Tab and Find cookie. Click on Cookie
After that you plug each of the values in their respective places 
nhentai --cookie="csrftoken={CSRTOKEN};sessionid={SESSIONID};cf_clearance={CF_CLEARANCE}" 
After that you then go whatismybrowser.com. This will give you you're browser useragent.
Copy and paste that value into this command and run it.
nhentai --useragent="{USERAGENT}"
After that you're username should pop up when running the command and you should be able to download and search for filtered files.

**Comment by noonealive1** [comment]
(tutorial_env) C:\Users\HP>nhentai --useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0"
[22:55:28] [INFO] nHentai ver 0.4.16: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

Usage:
  nhentai --search [keyword] --download
  NHENTAI=http://h.loli.club nhentai --id [ID ...]
  nhentai --file [filename]

Environment Variable:
  NHENTAI                 nhentai mirror url

nhentai: error: no such option: --useragent

i have saved the cookie and it shows cookie saved but when i try to change useragent, above happens 
and the download error still exists

**Comment by noonealive1** [comment]
thank you all for helping and not helping
i solved my problem by 
"pip install --upgrade nhentai"
so my bad 
thanks for software RicterZ
