### ISSUE TITLE
Possible issue with requests

### ISSUE THREAD

**Issue by Spyridion** [RicterZ/nhentai#276]
Hi, I'm getting a key error with the init_response dictionary. Here's the error I got.
```
[00:05:13] banner: nHentai ver 0.5.2: あなたも変態。 いいね?
[00:05:13] main: Using mirror: https://nhentai.net
[00:05:13] main: Using viewer template "default"
[00:05:13] check_cookie: Cannot get your username, please check your cookie or use `nhentai --cookie` to set your cookie
[00:05:13] main: Using default language: japanese
Traceback (most recent call last):
  File "/usr/local/bin/nhentai", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.2', 'console_scripts', 'nhentai')())
  File "/usr/local/lib/python3.10/dist-packages/nhentai-0.5.2-py3.10.egg/nhentai/command.py", line 58, in main
    doujinshis = _search_parser(options.keyword, sorting=options.sorting, page=page_list,
  File "/usr/local/lib/python3.10/dist-packages/nhentai-0.5.2-py3.10.egg/nhentai/parser.py", line 283, in search_parser
    page = range(1, init_response['num_pages']+1)
KeyError: 'num_pages'
```

**Comment by RicterZ** [comment]
Please provide your command for me to reproduct this issue

**Comment by Spyridion** [comment]
Hey, sorry for the late reply. I'm not sure what solved it, but moving over to your docker image worked all of the sudden.

**Comment by Spyridion** [comment]
Hi, I'm reopening this because I met the same issue again. Here's the command I used: docker run --rm -it -v X:/temp/[kemonono]/en:/output -v X:/temp/.nhentai/:/root/.nhentai ricterz/nhentai --search="artist:kemonono" --format '[%i]%t' --page-all --download

**Comment by Spyridion** [comment]
I found another command that's failing with the same error as well. 

`docker run --rm -it -v D:/temp/[akino-sora]/jp:/output -v D:/temp/.nhentai/:/root/.nhentai ricterz/nhentai --search="artist:akino-sora" --format '[%i]%t' --page-all --download`

**Comment by RicterZ** [comment]
It's nhentai.net website's bug, some sorting ways are not working on API. A workaround is adding `--sort=recent` option.
```
(nhentai-py3.12) /m/c/U/S/P/nhentai >>> python -m nhentai.command --search="artist:akino-sora" --format '[%i]%t' --page-
all --download --output /tmp/ --sort=recent
[00:18:05] banner: nHentai ver 0.5.7: あなたも変態。 いいね?
[00:18:05] main: Using mirror: https://nhentai.net
[00:18:05] main: Using proxy: http://192.168.13.1:7890
[00:18:05] main: Using viewer template "default"
[00:18:06] check_cookie: Login successfully! Your username: ricter-z
[00:18:09] search_parser: Searching doujinshis using keywords "artist:akino-sora" on page 1/6
[00:18:11] search_parser: Request URL: https://nhentai.net/api/galleries/search?query=artist%3Aakino-sora&page=1&sort=recent
[00:18:12] search_parser: Response: {'result': [{'id': 523493, 'media_id': '3016479', 'title': {'english': "[Akino Sora] Isekai Kita node Sukebe Skill de Zenryoku Ouka Shiyou to Omou 11Shame | I Came to Another World, So I Think I'm Gonna Enjoy My Sex Skills to the Fullest! 11th Shot [Digital Tokusouban] [English] [Cali]", 'japanese': '[あきのそら] 異世界来 たのでスケベスキルで全力謳歌しようと思う 11射目 [デジタル特装版] [DL版] [英訳]', 'pretty': "Isekai Kita node Sukebe Skill de Zenryoku Ouka Shiyou to Omou 11Shame | I Came to Another World, So I T...
```
