### ISSUE TITLE
not downloading!

### ISSUE THREAD

**Issue by Aditya331** [RicterZ/nhentai#285]
PS D:\programs\nhentai> nhentai --file codes.txt --pdf
Traceback (most recent call last):
  File "C:\Users\aj165\AppData\Local\Programs\Python\Python311\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.3', 'console_scripts', 'nhentai')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aj165\AppData\Local\Programs\Python\Python311\Scripts\nhentai-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^
StopIteration

**Comment by JTN02** [comment]
I am having the same issue did you ever find a solution?

**Comment by RicterZ** [comment]
Try:
```
pip3 uninstall nhentai
pip3 install nhentai
```

#300

**Comment by RicterZ** [comment]
Not a nhentai problem, ref: https://stackoverflow.com/questions/62579080/issue-with-loading-entry-point-possibly-connected-to-version-including-dev-tag
