### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by JTN02** [RicterZ/nhentai#300]
I keep getting this error. everything seems to download successfully but whenever I try to use the GUI or the "nhentai" in CMD I get this error.

`Traceback (most recent call last):
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python310\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.3', 'console_scripts', 'nhentai')())
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python310\Scripts\nhentai-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration`

**Comment by RicterZ** [comment]
https://stackoverflow.com/questions/62579080/issue-with-loading-entry-point-possibly-connected-to-version-including-dev-tag
