### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Shibuya5** [RicterZ/nhentai#302]
really i think i'm stupid today
any idea with that syntax error ? already tried to pip uninstall and intall it again

```
PS R:\Wpz\Nhdown> python
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> nhentai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'nhentai' is not defined

>>> nhentai --id 123855
  File "<stdin>", line 1
    nhentai --id 123855
                 ^^^^^^
SyntaxError: invalid syntax
>>>

```

**Comment by RicterZ** [comment]
Use this command in cmd.exe console not python console

Best Regards,
Ricter Zheng


Shibuya5 ***@***.***> 于2024年2月9日周五 03:46写道：

**Comment by Shibuya5** [comment]
Thank you !
