### ISSUE TITLE
Connection aborted 

### ISSUE THREAD

**Issue by thiendt2k1** [RicterZ/nhentai#332]
Hi, i got a connection aborted error when try to download all fav using argument as below, i am using Python version 3.10, Win 11, nhentai 0.5.5
```
nhentai --download -F --delay 1 --page-all > fav.txt
``` 

<details>Error, connection aborted<summary>Details</summary>
<p>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\requests-2.32.3-py3.10.egg\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\urllib3-2.2.2-py3.10.egg\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.5', 'console_scripts', 'nhentai')())
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\nhentai-0.5.5-py3.10.egg\nhentai\command.py", line 38, in main
    check_cookie()
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\nhentai-0.5.5-py3.10.egg\nhentai\utils.py", line 34, in check_cookie
    response = request('get', constant.BASE_URL)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\nhentai-0.5.5-py3.10.egg\nhentai\utils.py", line 30, in request
    return getattr(session, method)(url, verify=False, **kwargs)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\requests-2.32.3-py3.10.egg\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\requests-2.32.3-py3.10.egg\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\requests-2.32.3-py3.10.egg\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\Desktop\nhen\nhentai\venv\lib\site-packages\requests-2.32.3-py3.10.egg\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

</p>
</details>

**Comment by thiendt2k1** [comment]
Never mind, nhentai in my country is blocked by my isp, i apply vpn to OS and it work ok now
