### ISSUE TITLE
PDFs Not Being Generated for Specific Titles

### ISSUE THREAD

**Issue by EZ-Melon** [RicterZ/nhentai#335]
While attempting to download #414005 with the following syntax <nhentai --id 414005 --pdf --format="(%i) - %p" --rm-origin-dir>, I noticed that the portion of the title in [], as evidenced in the first screenshot, wasn't being removed, which is causing the pdf to not create properly. The folder is being created properly, so I'm not sure why I'm getting a FileNotFoundError

**Title**
![Title](https://github.com/user-attachments/assets/fe57128a-8c93-46bd-b85a-6c9862564ca0)

**FileNotFoundError**
![FileNotFoundError](https://github.com/user-attachments/assets/1de8a4f0-ef59-47f5-bb52-b6f0f3c29f65)

**Folder**
![Folder](https://github.com/user-attachments/assets/9e51a5fc-2bd0-4df4-95b6-10f94ce1270c)

**Comment by edgar1016** [comment]
I couldn't reproduce this but I noticed you're using nhentai version 5.5.3 try installing 5.5.5 manually by 
- downloading and extracting the repo
- open a command prompt and navigate to the extracted folder
- run `pip uninstall nhentai`
- run `pip install -r requirements.txt`
- run `python setup.py install`

That should install 5.5.5, pip only installs up to 5.5.3 it's working on my end with that version.

**Comment by EZ-Melon** [comment]
This didn't work as I'm still getting the below error

[19:32:42] generate_pdf: Writing PDF file to path: ./(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an…\..\(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an….pdf
Traceback (most recent call last):
  File "\\?\C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.5', 'console_scripts', 'nhentai')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\nhentai-0.5.5-py3.12.egg\nhentai\command.py", line 105, in main
    generate_pdf(options.output_dir, doujinshi, options.rm_origin_dir, options.move_to_folder)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\nhentai-0.5.5-py3.12.egg\nhentai\utils.py", line 224, in generate_pdf
    with open(pdf_filename, 'wb') as pdf_f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an…\\..\\(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an….pdf'

**Comment by RicterZ** [comment]
@EZ-Melon `i.nhentai.net` is the pics CDN server, the mirrors should be contains those CDN servers, please refer to https://github.com/RicterZ/nhentai?tab=readme-ov-file#nhentai-mirror

**Comment by EZ-Melon** [comment]
This is still occurring on 0.5.7. Please examine the console output below for more details.

`Microsoft Windows [Version 10.0.19045.4780]
(c) Microsoft Corporation. All rights reserved.

C:\Users\<user>\Desktop\Misc\Favorites>nhentai --id 414005 --pdf --format="(%i) - %p" --rm-origin-dir
[16:27:29] banner: nHentai ver 0.5.7: あなたも変態。 いいね?
[16:27:29] main: Using mirror: https://nhentai.net
[16:27:29] main: Using viewer template "default"
[16:27:30] check_cookie: Login successfully! Your username: <user>
[16:27:30] doujinshi_parser: Fetching doujinshi information of id 414005
[16:27:31] download: Starting to download doujinshi: [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) | The Virgin Onee-San (29) From Next-Door and I [English]
[16:27:31] start_download: Doujinshi will be saved at "./(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an…"
[16:27:34] download: Starting to download https://i.nhentai.net/galleries/2292293/1.jpg ...
[16:27:34] download: Starting to download https://i.nhentai.net/galleries/2292293/2.jpg ...
[16:27:34] download: Starting to download https://i.nhentai.net/galleries/2292293/3.jpg ...
[16:27:34] download: Starting to download https://i.nhentai.net/galleries/2292293/4.jpg ...
[16:27:34] download: Starting to download https://i.nhentai.net/galleries/2292293/5.jpg ...
[16:27:35] download: Starting to download https://i.nhentai.net/galleries/2292293/6.jpg ...
[16:27:35] download: Starting to download https://i.nhentai.net/galleries/2292293/7.jpg ...
[16:27:35] download: Starting to download https://i.nhentai.net/galleries/2292293/8.jpg ...
[16:27:36] download: Starting to download https://i.nhentai.net/galleries/2292293/9.jpg ...
[16:27:36] download: Starting to download https://i.nhentai.net/galleries/2292293/10.jpg ...
[16:27:36] download: Starting to download https://i.nhentai.net/galleries/2292293/11.jpg ...
[16:27:37] download: Starting to download https://i.nhentai.net/galleries/2292293/12.jpg ...
[16:27:37] download: Starting to download https://i.nhentai.net/galleries/2292293/13.jpg ...
[16:27:37] download: Starting to download https://i.nhentai.net/galleries/2292293/14.jpg ...
[16:27:37] download: Starting to download https://i.nhentai.net/galleries/2292293/15.jpg ...
[16:27:38] download: Starting to download https://i.nhentai.net/galleries/2292293/16.jpg ...
[16:27:39] download: Starting to download https://i.nhentai.net/galleries/2292293/17.jpg ...
[16:27:39] download: Starting to download https://i.nhentai.net/galleries/2292293/18.jpg ...
[16:27:39] download: Starting to download https://i.nhentai.net/galleries/2292293/19.jpg ...
[16:27:39] download: Starting to download https://i.nhentai.net/galleries/2292293/20.jpg ...
[16:27:40] download: Starting to download https://i.nhentai.net/galleries/2292293/21.jpg ...
[16:27:40] download: Starting to download https://i.nhentai.net/galleries/2292293/22.jpg ...
[16:27:40] download: Starting to download https://i.nhentai.net/galleries/2292293/23.jpg ...
[16:27:41] download: Starting to download https://i.nhentai.net/galleries/2292293/24.jpg ...
[16:27:41] download: Starting to download https://i.nhentai.net/galleries/2292293/25.jpg ...
[16:27:41] download: Starting to download https://i.nhentai.net/galleries/2292293/26.jpg ...
[16:27:41] download: Starting to download https://i.nhentai.net/galleries/2292293/27.jpg ...
[16:27:41] download: Starting to download https://i.nhentai.net/galleries/2292293/28.jpg ...
[16:27:43] download: Starting to download https://i.nhentai.net/galleries/2292293/29.jpg ...
[16:27:43] download: Starting to download https://i.nhentai.net/galleries/2292293/30.jpg ...
[16:27:43] download: Starting to download https://i.nhentai.net/galleries/2292293/31.jpg ...
[16:27:46] generate_pdf: Writing PDF file to path: ./(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an…\..\(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an….pdf
Traceback (most recent call last):
  File "\\?\C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.7', 'console_scripts', 'nhentai')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\nhentai-0.5.7-py3.12.egg\nhentai\command.py", line 105, in main
    generate_pdf(options.output_dir, doujinshi, options.rm_origin_dir, options.move_to_folder)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\nhentai-0.5.7-py3.12.egg\nhentai\utils.py", line 225, in generate_pdf
    with open(pdf_filename, 'wb') as pdf_f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an…\\..\\(414005) - [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an….pdf'`

**Comment by edgar1016** [comment]
Do you have img2pdf installed in pyhon? Try typing `img2pdf` in the console to see if it's installed. If it's not trying installing it by typing `pip install img2pdf` in the console.

**Comment by EZ-Melon** [comment]
I do have img2pdf installed. Most other files I try to download work no problem, so I'm not sure what's going on.

**Comment by edgar1016** [comment]
Not sure what's going on only other thing I can think of I remember someone having a similar issue because of their python version, I think they either upgraded or downgraded to get it working. Which version of python are you using?

**Comment by EZ-Melon** [comment]
I'm using 3.12
