### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by DukeValentine** [RicterZ/nhentai#36]
When I attempt to download from my favorites, some of the doujinshi give the error referenced in the title.

Version:
`0.2.18`

Command:
 `nhentai --login username:password  --download`

Output:
```
[22:14:53] [INFO] Fetching information of doujinshi id 250158
[22:14:53] [CRITICAL] No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "/usr/local/lib/python2.7/dist-packages/nhentai-0.2.18-py2.7.egg/nhentai/parser.py", line 108, in doujinshi_parser
    exit(1)
  File "/usr/lib/python2.7/site.py", line 366, in __call__
    raise SystemExit(code)
SystemExit: 1
[22:14:53] [INFO] Fetching information of doujinshi id 250161
[22:14:53] [CRITICAL] No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "/usr/local/lib/python2.7/dist-packages/nhentai-0.2.18-py2.7.egg/nhentai/parser.py", line 108, in doujinshi_parser
    exit(1)
  File "/usr/lib/python2.7/site.py", line 366, in __call__
    raise SystemExit(code)
SystemExit: 1
[22:14:53] [CRITICAL] No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "/usr/local/lib/python2.7/dist-packages/nhentai-0.2.18-py2.7.egg/nhentai/parser.py", line 108, in doujinshi_parser
    exit(1)
  File "/usr/lib/python2.7/site.py", line 366, in __call__
    raise SystemExit(code)
SystemExit: 1
```

**Comment by RicterZ** [comment]
Sorry, I cannot reproduct it. What's mirror of nhentai do you use? Please try nhentai.net

**Comment by RicterZ** [comment]
You can checkout the CI log: https://travis-ci.org/RicterZ/nhentai/jobs/450483234
It's working normally.

**Comment by RicterZ** [comment]
Ok, thanks
