### ISSUE TITLE
Parsing of favorite_counts ends up with NoneType is not callable exception.

### ISSUE THREAD

**Issue by DennouNeko** [RicterZ/nhentai#365]
It looks like version 0.4.18 of nhentai tool is stopping to work. At first it was just from time to time, but now I just kept getting "Tried yo get image id failed" every time.
I've tried updating to most recent 0.5.17. Pip installation didn't generate the executable in scripts, but at least manual instalation worked.
The tool was now giving me exception while parsing favorite_counts, regardless if I was downloading favorites or doujin directly from ID.
```
Traceback (most recent call last):
  File "\\?\C:\Program Files\Python312\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.17', 'console_scripts', 'nhentai')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\nhentai\command.py", line 84, in main
    doujinshi_info = doujinshi_parser(doujinshi_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\nhentai\parser.py", line 152, in doujinshi_parser
    doujinshi['favorite_counts'] = favorite_counts.strip()
                                   ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

After a bit of investigation, it seems like there's just a small mistake in parser.py.
Line 152 should be changed from
```
    doujinshi['favorite_counts'] = favorite_counts.strip()
```
to
```
    doujinshi['favorite_counts'] = favorite_counts.text.strip()
```

And just in case, using the nHentai GUI v1.06 on Windows 10 with Python 3.12.

**Comment by DennouNeko** [comment]
Never mind... Seems like the issue was caused by fiddling around and overwriting the git verrsion with pip update. Git version has all the necessary fixes.
It's the 0.5.17 available from pip that causes the exception to happen.

**Comment by denny1151** [comment]
Hello, I also encountered the issue "Tried to get image id failed."
I'm not sure how to solve it. I'm currently using nhentai-GUI.
Could I ask how you dealt with this problem?
Additionally, I was able to use it normally about four months ago.

Sorry, I really don't understand these programming languages.

**Comment by DennouNeko** [comment]
The fix for me was to update the nhentai tool. Preferably you should uninstall any and all pip versions (if you have any) and install the one from git since pip installation of versions other than 0.4.18 doesn't create the executable that GUI needs (as reported in #364).

As for v0.4.18 itself, it seems like structure of website slightly changed and that version wasn't robust enough to handle it, but I'd have to take a closer look. Though it would explain why it was working fine up to certain point.

**Comment by RicterZ** [comment]
I think this should be fixed already?

**Comment by RicterZ** [comment]
I'm abroad so that I cannot push a fix commit, if the problem is figured out could you submit a pull request for this bug?

**Comment by DennouNeko** [comment]
I did notice that it has been fixed in git already, but for some reason installation with pip grabs version that still has the issue. I've made sure just now that it still happens.
It seems that pip installs [this commit](https://github.com/RicterZ/nhentai/commit/bb41e502c1cf5d772f61311bab36e824dd591f2e) because it has the updated version string, but not the next one with fix for #361 that was committed the same day.
So there's nothing to fix on git side.

**Comment by RicterZ** [comment]
Seem need a new release on pypi?

Best Regards,
Ricter Zheng


DennouNeko ***@***.***>于2025年1月6日 周一19:40写道：

**Comment by DennouNeko** [comment]
Pretty much. That should fix the issue with pip install.

**Comment by RicterZ** [comment]
Publish a new version `0.5.17.1`, could you try it again?

**Comment by DennouNeko** [comment]
pip downloaded v0.5.17.2, I guess there was one more version published in the mean time :)
I did remove any other versions before checking and got good news - it did create the executable in Scripts folder and download with GUI worked properly.
