### ISSUE TITLE
AttributeError on retrieving doujin favorites list

### ISSUE THREAD

**Issue by Darkshadows9** [RicterZ/nhentai#50]
When trying to download in bulk from my favorites list, I will get a series of the exact same error in a row:
```
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai-0.3.0-py3.7.egg\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
```
When trying to download the same doujins individually or through a text list, it does not reproduce the error. My assumption is that --download is trying to grab the doujins too fast and is not retrieving the proper data somehow. Doing it by a file list parses the doujins much slower and correctly.

Commands tested to try and reproduce:
```
nhentai --threads=1 --login=username:password --download #bug here
nhentai --threads=1 --login=username:password --file=doujinshi.txt #no bug
```

doujinshi.txt and my favorites list have the exact same contents to test, the 30 most recently submitted doujins.

A thing to consider is simply the possibility of detecting a failure in retrieval and retrying. Another is adding a --wait flag to simply wait between parsing doujins.

**Comment by RicterZ** [comment]
You should specify your username and password of your nhentai account.

**Comment by RicterZ** [comment]
```
⋊> /m/c/U/R/P/nhentai on master ⨯ python -m nhentai.command --threads=1 --login=nhentai_test:nhentai --download
[03:29:56] [INFO] nHentai ver 0.3.1: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[03:29:56] [INFO] Using mirror: https://nhentai.net
[03:29:56] [INFO] Logging in to nhentai using credential pair 'nhentai_test:*******'
[03:29:58] [INFO] You have 3 favorites in 1 pages.
[03:29:58] [INFO] Getting doujinshi ids of page 1
[03:29:58] [INFO] Fetching doujinshi information of id 261100
[03:29:58] [INFO] Fetching doujinshi information of id 243647
[03:29:58] [INFO] Fetching doujinshi information of id 242049
[03:29:59] [ERROR] Ctrl-C signal received. Stopping...
```

I cannot reproduct this bug.

**Comment by RicterZ** [comment]
Try upgrade to 0.3.1 via `pip install nhentai -U`

**Comment by Darkshadows9** [comment]
Initial tests were done on 0.3.1. Verified that there were no updates available and that pip check was correct.

Issue was only found with doujins in large quantities from favorites.

```
C:\Users\Darkshadows>nhentai --threads=1 --login=[username]:[password] --download
[15:24:18] [INFO] nHentai ver 0.3.1: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[15:24:18] [INFO] Using mirror: https://nhentai.net
[15:24:18] [INFO] Logging in to nhentai using credential pair 'Darkshadows:*********'
[15:24:19] [INFO] You have 31 favorites in 2 pages.
[15:24:19] [INFO] Getting doujinshi ids of page 1
[15:24:19] [INFO] Fetching doujinshi information of id 268958
[15:24:19] [INFO] Fetching doujinshi information of id 268959
[15:24:19] [INFO] Fetching doujinshi information of id 268960
[15:24:19] [INFO] Fetching doujinshi information of id 268961
[15:24:19] [INFO] Fetching doujinshi information of id 268962
[15:24:19] [INFO] Fetching doujinshi information of id 268963
[15:24:19] [INFO] Fetching doujinshi information of id 268964
[15:24:19] [INFO] Fetching doujinshi information of id 268965
[15:24:19] [INFO] Fetching doujinshi information of id 268966
[15:24:19] [INFO] Fetching doujinshi information of id 268967
[15:24:19] [INFO] Fetching doujinshi information of id 268968
[15:24:19] [INFO] Fetching doujinshi information of id 268969
[15:24:19] [INFO] Fetching doujinshi information of id 268970
[15:24:20] [INFO] Fetching doujinshi information of id 268971
[15:24:20] [INFO] Fetching doujinshi information of id 268972
[15:24:20] [INFO] Fetching doujinshi information of id 268973
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [INFO] Fetching doujinshi information of id 268974
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
[15:24:20] [INFO] Fetching doujinshi information of id 268975
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [INFO] Fetching doujinshi information of id 268976
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [INFO] Fetching doujinshi information of id 268977
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [INFO] Fetching doujinshi information of id 268978
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [INFO] Fetching doujinshi information of id 268979
[15:24:20] [INFO] Fetching doujinshi information of id 268980
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [INFO] Fetching doujinshi information of id 268981
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [INFO] Fetching doujinshi information of id 268982
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "c:\program files\python37\lib\site-packages\nhentai\parser.py", line 132, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'
[15:24:20] [ERROR] Ctrl-C signal received. Stopping...
```

**Comment by symant233** [comment]
Same here, `pip install nhentai -U` doesn't work.

**Comment by RicterZ** [comment]
Try `pip install nhentai==0.3.1`. 
I can reproduce this bug now, it maybe access frequency limitation of nhentai, I'm fixing it now.

**Comment by RicterZ** [comment]
Cloudflare returns 503 if you request to fast, I reduct the threads number and add retry mechanism.
nhentai is not very
